### PR TITLE
MATH-1825: Handle subtract button exception

### PR DESCRIPTION
**Pull request by iljackibarra**
Closes [MATH-1825](https://imaginelearning.atlassian.net/browse/MATH-1825)

**Purpose**
Pressing the (^) after a subtract sign (-), causes the next click to crash. On lesson player, this brings up the Something went wrong screen. Locally, you cannot press any other buttons. This fix allows you to do this without raising any exception .

**To QA**

1. Open the calculator in lesson-player
2. Press - (Subtract) button once
3. Press the `^` button once
4. Press any other button

### CODE REVIEW

**Comment by james-west-il** [comment]
Also, just checking, this means once you press the (^) you are committed to use the exponent.  Would it be better to replace the current operator with the last one you pressed?  This could be a future discussion if we want to overhaul the entire calculator.

**Comment by iljackibarra** [comment]
@james-west-il Sum, multiplication and division are not raising exceptions. They are already handled from ttm-coffeescript-math project.
As we are unable to build that project, I handled the exception from this project.

**Comment by kamnayadavIL** [comment]
I think we should add a few tests around this scenario with the '-' operator as well as other operators that we have. The build keeps erroring out on my machine when trying to build. Please let me know how you feel about the tests.

**Comment by kamnayadavIL** [comment]
Assigning to Jack so he can add the tests.

**Comment by kamnayadavIL** [comment]
As per discussion with Jack and James, this needs to be fixed some more. The current behavior where hitting 'subtraction' operator before hitting any number causes a behavior different from addition, multiplication and division operators. Assigning it to Jack and marking as WIP.

**Comment by james-west-il** [comment]
@kamnayadavIL Now with version bumping.

**Pull request merged**
