### PR TITLE
MA-182: Calculator acc

### PR DESCRIPTION
**Pull request by zeusdev001**
Closes [MA-181](https://imaginelearning.atlassian.net/browse/MA-181)
Closes [MA-179](https://imaginelearning.atlassian.net/browse/MA-179)
Closes [MA-28](https://imaginelearning.atlassian.net/browse/MA-28)

## Acceptance Criteria
- [x] calculator numbers and operations should be accessible using keyboard.
- [x] calculator buttons should have aria-labels.
- [x] When the content on the display is changed, the updated content should be announced to the 
     users by the screen readers. 

## Dependency
- https://github.com/thinkthroughmath/lesson-player-docker/pull/86 needs to point to the new calculator verison
- https://github.com/thinkthroughmath/equation-builder/pull/11 possibly dependent on this?

### CODE REVIEW

**Comment by andrewpatterson3001** [comment]
@zeusdev001 can you please include your steps to demo and review these changes?

cc @hinghing15

**Comment by zeusdev001** [comment]
> @zeusdev001 can you please include your steps to demo and review these changes?
> 
> cc @hinghing15

To verify this ticket you can follow the following steps:
1. Launch NVDA and the calculator in the lesson player.
2. Arrive on the References section using the keyboard.
3. Use the number pad or the number keys on top of the keyboard to provide input into the calculator.
4. Use the tab key to navigate to the calculator buttons and verify the labels that have been added.
5. NVDA will read the results of the operations performed in the calculator.
6. Use the ESC key to close the References section.

**Comment by kamnayadavIL** [comment]
@zeusdev001 @zeusdev002 When the user presses the `=` button, can we announce the whole equation like we're doing for other button presses? 
For instance, here it would read `3 times 6 equals 18`? Is that a good/common practice for WCAG 2.1 standards? 

image

**Comment by kamnayadavIL** [comment]
Other than this suggestion, the changes look good. We would have to use https://github.com/thinkthroughmath/lesson-player-docker/pull/86 PR when bringing up the staging environment or when merging this PR.

**Comment by andrewpatterson3001** [comment]
@itobler Kamna has also tested this, please see screenshot above

**Pull request merged**
