### PR TITLE
[#8771535]When a root is followed by another operation process crashes

### PR DESCRIPTION
**Pull request by ninjapanzer**
This is a good failing test to triage where in the calculator lp ttm-math
stack things are bwoken

in part with https://github.com/thinkthroughmath/ttm-coffeescript-math/pull/7

This one test will fail until https://github.com/thinkthroughmath/ttm-coffeescript-math/pull/7 is merged

### CODE REVIEW

**Comment by ninjapanzer** [comment]
@joelmccracken this is just a test to cover the test failure for #8771535

**Comment by srobbibaro** [comment]
Test looks good to me. It's very straight forward. With respect to merging it in, are we okay with leaving a failing test on this repo without providing a solution?

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
Well the solution is over in ttm-coffeescript-math this was more diagnostic than anything else because this is where the bug was exposed

**Comment by srobbibaro** [comment]
So you'd expect the test to pass once that code is merged in?

**Comment by ninjapanzer** [comment]
that is exactly the case as noted in the description

**Comment by srobbibaro** [comment]
Sorry - the intent of my questions are really around when this should be merged in. Should we wait until after the other ticket is merged or whenever review has signed off?

**Comment by ninjapanzer** [comment]
Its not directly dependent but of we can wait we should

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
I am going to join this with #21

**Pull request closed without merging**
