### PR TITLE
bumping package versions with update of ttm-coffeescript-math

### PR DESCRIPTION
**Pull request by ninjapanzer**
### What am I?
Test to verify feature bug from ttm-coffeescript-math

Version increases to include the updates from https://github.com/thinkthroughmath/ttm-coffeescript-math/pull/7

WIP until https://github.com/thinkthroughmath/ttm-coffeescript-math/pull/7

This will fail until https://github.com/thinkthroughmath/ttm-coffeescript-math/pull/7

### After merge
create a release for 0.4.13

### CODE REVIEW

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
I am just going to move these reviews from the old branch here to speed things up
Code review assigned to dev(s): @robwierzbowski, @srobbibaro

**Comment by robwierzbowski** [comment]
All good from me!

**Pull request merged**
